export const LEGACY_SONG_CARD_TITLES = new Set([
  "”Waterloo” vinner Eurovision",
  "”Dancing Queen” släpps",
  "”Levels” släpps",
  "”Euphoria” vinner Eurovision",
  "”Wake Me Up” släpps",
  "”Dancing On My Own” släpps",
  "”Tattoo” vinner Eurovision",
  "”The Final Countdown” släpps",
  "”Sommartider” släpps",
  "”Öppna landskap” släpps",
  "”Främling” slår igenom",
  "”Fångad av en stormvind” vinner Eurovision",
  "”Lovefool” släpps",
  "”Boten Anna” släpps",
  "”Jag kommer” släpps",
  "”Heroes” vinner Eurovision",
  "”Staten och kapitalet” släpps",
  "”Diggi-loo diggi-ley” vinner Eurovision",
  "”Take Me to Your Heaven” vinner Eurovision",
  "”Dom andra” släpps",
  "”Sakta vi gå genom stan” släpps",
  "”Sånt är livet” släpps",
  "”Stad i ljus” vinner Melodifestivalen",
  "”Himlen runt hörnet” släpps",
  "”Aserejé” blir sommarplåga",
  "”Den vilda” vinner Melodifestivalen",
]);
